# Generated by Django 2.1.4 on 2018-12-10 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_story_storyblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story_blurb',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='story',
            name='story_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='story',
            name='user_creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storyblock',
            name='body_text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='storyblock',
            name='story',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.Story'),
        ),
    ]
