# Generated by Django 2.1.4 on 2018-12-23 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181210_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='user_creator',
        ),
        migrations.RemoveField(
            model_name='storyblock',
            name='story',
        ),
        migrations.DeleteModel(
            name='Story',
        ),
        migrations.DeleteModel(
            name='StoryBlock',
        ),
    ]
